steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  # - name: node
  #   entrypoint: npm
  #   args: ["test"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-north1-docker.pkg.dev/playground-341718/react-demo-chat/fe",
        "-f",
        "Dockerfile-fe",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-north1-docker.pkg.dev/playground-341718/react-demo-chat/fe",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "react-demo-chat-fe",
        "--image",
        "europe-north1-docker.pkg.dev/playground-341718/react-demo-chat/fe",
        "--region",
        "europe-north1",
        "--port",
        "80",
      ]
images:
  - europe-north1-docker.pkg.dev/playground-341718/react-demo-chat/fe
