FROM node:18 AS react-app
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run dev:build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=react-app /usr/src/app/dist .

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
